# Generated by Django 3.1.7 on 2021-03-18 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jaegerserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaegerserver.sighting')),
            ],
        ),
    ]
