# Generated by Django 3.1.7 on 2021-03-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaegerserver', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='monsters',
            field=models.ManyToManyField(related_name='locations', to='jaegerserver.Monster'),
        ),
    ]
