# Generated by Django 3.1.7 on 2021-03-18 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jaegerserver', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='history',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
