# Generated by Django 3.1.7 on 2021-03-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaegerserver', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='history',
            field=models.CharField(default='GAREASDFASDAFASDFF', max_length=1000),
        ),
        migrations.AddField(
            model_name='monster',
            name='danger_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='features',
            field=models.JSONField(default=['Classified']),
        ),
    ]
