# Generated by Django 3.1.7 on 2021-03-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaegerserver', '0003_auto_20210319_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='features',
            field=models.JSONField(verbose_name={}),
        ),
    ]
