# Generated by Django 3.1.7 on 2021-03-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaegerserver', '0004_auto_20210319_1134'),
        ('jaegerserver', '0003_location_monsters'),
    ]

    operations = [
    ]
