# Generated by Django 3.1.7 on 2021-03-19 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jaegerserver', '0006_auto_20210319_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='day',
            new_name='date',
        ),
        migrations.AddField(
            model_name='monster',
            name='about',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sighting',
            name='description',
            field=models.CharField(default='.', max_length=2000),
            preserve_default=False,
        ),
    ]
