# Generated by Django 3.1.7 on 2021-03-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaegerserver', '0007_auto_20210319_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='day',
            field=models.CharField(default='day', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateTimeField(max_length=20),
        ),
    ]
